# Site settings
title: Sam Brady
description: a compilation of full-stack projects by Sam Brady
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://sambrady.me" # the base hostname

# User settings
username: Sam Brady
user_description: I am a full-stack software developer living in Chicago with a teaching background and degrees in Political Science, English Literature, and Education. I entered tech to see what else was out there. Turns out, there's a lot!
user_title: Software Developer
email: sambrady0652@gmail.com
# twitter_username: lorem_ipsum
github_username:  sambrady0652
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
